import re
#import long_responses as long

def message_probability(user_message, recognised_words, single_response=False, required_words=[]):
    message_certainty = 0
    has_required_words = True

    for word in user_message:
        if word in recognised_words:
            message_certainty += 1
    # CALCULATES THE PERCENT OF RECOGNISED WORDS IN A USER MESSAGE
    percentage = float(message_certainty) / float(len(recognised_words))

    for word in required_words:
        if word not in user_message:
            has_required_words = False
            break
    if has_required_words or single_response:
        return int(percentage * 100)
    else:
        return 0

def check_all_messages(message):
    highest_prob_list = {}

    def response(bot_response, list_of_words, single_response=False, required_words=[]):
        nonlocal highest_prob_list
        highest_prob_list[bot_response] = message_probability(message, list_of_words, single_response, required_words)

    # Response................................................................................
    #response('hello!', ['hello', 'hi', 'sup', 'hey', 'heyo'], single_response=True)
    response('I\'m doing fine, and you?', ['how', 'are', 'You', 'doing'], required_words=['how'])
    response('Thank you!', ['i', 'love', 'code', 'palace'], required_words=['code', 'palace'])
    #additional responsis 
    response('I am a chatbot.', ['who', 'are', 'you'], required_words=['who'])
    response('The weather is nice today.', ['weather'], required_words=['weather'])
    response('I can help you with coding.', ['coding', 'help'], required_words=['coding'])
    response("That's interesting!", ["interesting"], required_words=["interesting"])
    response("I'm here to assist you.", ["assist", "help"], required_words=["assist"])
    response("Coding is a great skill to have.", ["coding", "skill"], required_words=["coding"])
    response("I enjoy our conversation.", ["enjoy", "conversation"], required_words=["enjoy"])
    response("Learning new things is always exciting.", ["learning", "exciting"], required_words=["learning"])
    response("Technology is advancing rapidly.", ["technology", "advancing"], required_words=["technology"])
    response("Curiosity is the key to learning.", ["curiosity", "learning"], required_words=["curiosity"])
    response("Stay curious and keep exploring!", ["stay", "curious", "exploring"], required_words=["curious"])
    response("I'm constantly learning and improving.", ["learning", "improving"], required_words=["learning"])
    response("Programming opens up a world of possibilities.", ["programming", "possibilities"], required_words=["programming"])
    response("Problem-solving is an essential skill in programming.", ["problem-solving", "programming"], required_words=["problem-solving"])
    response("Don't hesitate to ask if you have questions.", ["questions", "ask"], required_words=["questions"])
    response("I appreciate your curiosity.", ["appreciate", "curiosity"], required_words=["appreciate"])
    response("Keep up the good work!", ["keep up", "good work"], required_words=["keep up"])
    response("It's great to see your enthusiasm.", ["great", "enthusiasm"], required_words=["enthusiasm"])
    response("The journey of learning never ends.", ["journey", "learning"], required_words=["journey"])
    response("You're doing a fantastic job!", ["fantastic", "job"], required_words=["fantastic"])
    response("Let's explore the world of coding together.", ["explore", "coding"], required_words=["explore"])
    response("I'm here to make your coding journey enjoyable.", ["coding journey", "enjoyable"], required_words=["coding journey"])
    response("Never stop learning and growing.", ["never stop", "learning", "growing"], required_words=["never stop"])
    response("Embrace challenges as opportunities to learn.", ["embrace challenges", "opportunities", "learn"], required_words=["embrace challenges"])
    response("Coding is a blend of creativity and logic.", ["coding", "creativity", "logic"], required_words=["coding"])
    response("I'm glad to be part of your coding adventure.", ["coding adventure", "glad"], required_words=["coding adventure"])
    response("Success in coding comes with persistence.", ["success", "coding", "persistence"], required_words=["success"])
    response("Coding is a language that speaks to computers.", ["coding", "language", "computers"], required_words=["coding language"])
    response("Your dedication to coding is inspiring.", ["dedication", "coding", "inspiring"], required_words=["dedication"])
    response("Every line of code tells a story.", ["line of code", "tells a story"], required_words=["line of code"])
    response("Stay passionate about what you do.", ["stay passionate", "do"], required_words=["stay passionate"])
    response("In coding, the possibilities are limitless.", ["coding", "possibilities", "limitless"], required_words=["coding possibilities"])
    response("Your curiosity fuels the flame of knowledge.", ["curiosity", "flame of knowledge"], required_words=["curiosity"])
    response("Coding is like solving puzzles.", ["coding", "solving puzzles"], required_words=["coding"])
    response("Keep coding and creating!", ["keep coding", "creating"], required_words=["keep coding"])
    response("Coding is a journey of self-discovery.", ["coding", "journey", "self-discovery"], required_words=["coding journey"])
    response("I'm here to support your coding endeavors.", ["support", "coding endeavors"], required_words=["support"])
    response("Dive deep into the code and explore its magic.", ["dive deep", "code", "explore", "magic"], required_words=["dive deep"])
    # Additional responses
    response("Coding is a form of art.", ["coding", "art"], required_words=["coding"])
    response("The code you write reflects your thinking.", ["code", "thinking"], required_words=["code"])
    response("I'm fascinated by the power of algorithms.", ["power", "algorithms"], required_words=["algorithms"])
    response("Programming languages are like tools in a craftsman's workshop.", ["programming languages", "tools", "craftsman's workshop"], required_words=["programming languages"])
    response("Debugging is a skill that every coder masters over time.", ["debugging", "skill", "coder"], required_words=["debugging"])
    response("Learning from mistakes is an integral part of coding.", ["learning from mistakes", "coding"], required_words=["learning from mistakes"])
    response("The beauty of coding lies in its elegance and efficiency.", ["beauty", "coding", "elegance", "efficiency"], required_words=["coding elegance"])
    response("Coding is like a puzzle; each line of code fits into the bigger picture.", ["coding", "puzzle", "line of code", "bigger picture"], required_words=["coding puzzle"])
    response("The joy of coding is in creating something from nothing.", ["joy of coding", "creating", "something from nothing"], required_words=["joy of coding"])
    response("In coding, details matter. Pay attention to the little things.", ["coding", "details matter", "pay attention"], required_words=["coding details"])
    response("Code is a language that speaks to machines. Master it, and you're a storyteller.", ["code", "language", "speaks to machines", "storyteller"], required_words=["coding storyteller"])
    response("Programming is a dance between logic and creativity.", ["programming", "dance", "logic", "creativity"], required_words=["programming dance"])
    response("Coding is a journey of turning imagination into reality.", ["coding", "journey", "turning imagination into reality"], required_words=["coding journey"])
    response("Challenge yourself, and you'll discover the true extent of your abilities.", ["challenge yourself", "discover", "true extent", "abilities"], required_words=["challenge yourself"])
    response("The best coders are those who never stop asking 'why' and 'how.'", ["best coders", "never stop", "asking why", "asking how"], required_words=["best coders"])
    response("In the world of coding, curiosity is your compass.", ["world of coding", "curiosity", "compass"], required_words=["world of coding"])
    response("Coding is a perpetual learning journey. Embrace the unknown.", ["coding", "perpetual learning journey", "embrace the unknown"], required_words=["coding learning journey"])
    response("Coding is a blend of precision and creativity.", ["coding", "precision", "creativity"], required_words=["coding precision"])
    response("The more you code, the more you learn to speak the language of computers.", ["more you code", "more you learn", "speak the language", "computers"], required_words=["more you code"])
    response("The code you write today is the foundation for the programs of tomorrow.", ["code you write today", "foundation", "programs of tomorrow"], required_words=["code you write"])
    response("Coding is not just about solving problems; it's about crafting solutions.", ["coding", "solving problems", "crafting solutions"], required_words=["coding crafting"])
    response("In coding, persistence is the key to unlocking complex challenges.", ["coding", "persistence", "key", "unlocking complex challenges"], required_words=["coding persistence"])
    response("Code is a silent poetry that computers understand.", ["code", "silent poetry", "computers understand"], required_words=["coding poetry"])
    response("Coding is a symphony of logic and syntax.", ["coding", "symphony", "logic", "syntax"], required_words=["coding symphony"])
    response("Every coder has a unique coding style, like a signature in the digital world.", ["every coder", "unique coding style", "signature", "digital world"], required_words=["unique coding style"])
    response("Learning to code opens doors to endless possibilities and opportunities.", ["learning to code", "opens doors", "endless possibilities", "opportunities"], required_words=["learning to code"])
    response("Code with intention, and your programs will speak with purpose.", ["code with intention", "programs will speak", "with purpose"], required_words=["code with intention"])
    response("Coding is a dance of logic and imagination; move gracefully between them.", ["coding", "dance of logic", "imagination", "move gracefully"], required_words=["coding dance"])
    response("The coding community is a vast ocean of knowledge; dive in and explore.", ["coding community", "vast ocean of knowledge", "dive in", "explore"], required_words=["coding community"])
    response("Code is a tool, and a skilled coder is a craftsman.", ["code", "tool", "skilled coder", "craftsman"], required_words=["skilled coder"])
    response("Coding is not just about finding solutions; it's about creating elegant ones.", ["coding", "finding solutions", "creating elegant ones"], required_words=["coding creating elegant"])
    response("Every bug is an opportunity to enhance your debugging skills.", ["every bug", "opportunity", "enhance your debugging skills"], required_words=["debugging skills"])
    response("The more you code, the more you realize the infinite possibilities of technology.", ["more you code", "more you realize", "infinite possibilities", "technology"], required_words=["more you code"])
    response("Coding is a canvas; your programs are the masterpieces you paint.", ["coding", "canvas", "programs", "masterpieces"], required_words=["coding canvas"])
    response("The elegance of code lies in its simplicity and functionality.", ["elegance of code", "simplicity", "functionality"], required_words=["elegance of code"])
    response("Coding is a puzzle; each line of code brings you closer to the solution.", ["coding", "puzzle", "line of code", "closer to the solution"], required_words=["coding puzzle"])
    response("Your code tells a story; make it a captivating one.", ["code tells a story", "captivating one"], required_words=["code tells a story"])
    response("Coding is a journey of continuous improvement; every line of code is a step forward.", ["coding", "journey of continuous improvement", "every line of code", "step forward"], required_words=["coding continuous improvement"])
    response("Embrace the challenges in coding; they are stepping stones to mastery.", ["embrace the challenges", "coding", "stepping stones", "mastery"], required_words=["embrace the challenges"])
    response("The code you write reflects your thought process; make it clear and expressive.", ["code you write", "reflects", "thought process", "clear and expressive"], required_words=["code you write"])
    response("Coding is not just about instructions; it's about creating experiences.", ["coding", "instructions", "creating experiences"], required_words=["coding creating experiences"])
    response("Code is a conversation between the programmer and the computer; make it meaningful.", ["code", "conversation", "programmer and computer", "meaningful"], required_words=["code conversation"])
    response("Coding is a journey; enjoy the process, not just the destination.", ["coding", "journey", "enjoy the process", "not just the destination"], required_words=["coding journey"])
    response("The magic in coding is turning ideas into reality with just a few lines of code.", ["magic in coding", "turning ideas into reality", "few lines of code"], required_words=["magic in coding"])
    response("Code is the language of innovation; speak it fluently.", ["code", "language of innovation", "speak it fluently"], required_words=["code language"])
    response("Coding is a blend of creativity, logic, and a touch of madness.", ["coding", "blend of creativity", "logic", "touch of madness"], required_words=["coding blend"])
    response("Your code is your signature in the digital realm; make it unique and impactful.", ["code is your signature", "digital realm", "make it unique", "impactful"], required_words=["code is your signature"])
    response("Programming is not just about writing code; it's about solving real-world problems.", ["programming", "writing code", "solving real-world problems"], required_words=["programming solving real-world"])
    response("Code is the bridge between imagination and functionality; build it strong.", ["code", "bridge between imagination", "functionality", "build it strong"], required_words=["code bridge"])
    response("In coding, there's always more to learn; embrace the challenge of constant growth.", ["coding", "always more to learn", "embrace the challenge", "constant growth"], required_words=["coding constant growth"])
    response("The elegance of code is like poetry; each line contributes to the overall rhythm.", ["elegance of code", "poetry", "each line contributes", "overall rhythm"], required_words=["elegance of code"])
    response("Coding is a collaborative dance; every coder adds a unique move to the routine.", ["coding", "collaborative dance", "every coder adds", "unique move"], required_words=["coding collaborative dance"])
    response("Every error in coding is an opportunity to enhance your problem-solving skills.", ["every error", "coding", "opportunity", "enhance your problem-solving skills"], required_words=["coding problem-solving skills"])
    response("The canvas of coding is vast; paint your ideas with the brush of logic and creativity.", ["canvas of coding", "vast", "paint your ideas", "brush of logic and creativity"], required_words=["canvas of coding"])
    response("Code is the poetry of computers; make it resonate with clarity and purpose.", ["code", "poetry of computers", "make it resonate", "clarity and purpose"], required_words=["code poetry"])
    response("In the world of coding, there are no limits; explore, innovate, and create.", ["world of coding", "no limits", "explore", "innovate and create"], required_words=["world of coding"])
    response("Coding is not a sprint; it's a marathon of continuous improvement and learning.", ["coding", "not a sprint", "marathon of continuous improvement", "learning"], required_words=["coding marathon"])
    response("Your code is a reflection of your problem-solving skills; polish it with precision.", ["code is a reflection", "problem-solving skills", "polish it with precision"], required_words=["code is a reflection"])
    response("Coding is the art of turning imagination into executable reality.", ["coding", "art of turning imagination", "executable reality"], required_words=["coding art"])
    response("Code with purpose, and every line will contribute meaningfully to the project.", ["code with purpose", "every line will contribute", "meaningfully to the project"], required_words=["code with purpose"])
    response("Coding is a journey of discovery; each bug uncovered is a step closer to mastery.", ["coding", "journey of discovery", "each bug uncovered", "step closer to mastery"], required_words=["coding journey"])
    response("The symphony of coding is composed of logic, syntax, and a touch of innovation.", ["symphony of coding", "composed of logic", "syntax", "touch of innovation"], required_words=["symphony of coding"])
    response("Your code is like a sculpture; chisel away the unnecessary for a masterpiece.", ["code is like a sculpture", "chisel away the unnecessary", "masterpiece"], required_words=["code is like a sculpture"])
    response("Coding is a language; speak it fluently, and your programs will resonate.", ["coding", "language", "speak it fluently", "programs will resonate"], required_words=["coding language"])
    response("In coding, precision is your brush; paint with accuracy to create beautiful solutions.", ["coding", "precision is your brush", "paint with accuracy", "create beautiful solutions"], required_words=["coding precision"])
    response("Code is the vehicle of innovation; drive it with creativity and purpose.", ["code", "vehicle of innovation", "drive it with creativity", "purpose"], required_words=["code vehicle of innovation"])
    response("Coding is the journey of transforming ideas into executable reality.", ["coding", "journey of transforming ideas", "executable reality"], required_words=["coding journey"])
    response("Every line of code is a stroke of genius; paint a masterpiece with your logic.", ["every line of code", "stroke of genius", "paint a masterpiece", "your logic"], required_words=["stroke of genius"])
    response("Coding is a dance with complexity; step gracefully and turn challenges into solutions.", ["coding", "dance with complexity", "step gracefully", "turn challenges into solutions"], required_words=["coding dance"])
    response("The joy of coding is in the process, not just the end result.", ["joy of coding", "process", "not just the end result"], required_words=["joy of coding"])
    response("Coding is a language of innovation; speak it eloquently with every line.", ["coding", "language of innovation", "speak it eloquently", "every line"], required_words=["coding language"])
    response("In coding, every challenge is an invitation to explore and expand your skills.", ["coding", "every challenge", "invitation to explore", "expand your skills"], required_words=["coding challenge"])
    response("The language of computers is code; become fluent and articulate your ideas.", ["language of computers", "code", "become fluent", "articulate your ideas"], required_words=["language of computers"])
    response("Coding is a puzzle; solve it patiently, and every piece will fall into place.", ["coding", "puzzle", "solve it patiently", "every piece will fall into place"], required_words=["coding puzzle"])
    response("Your code is a reflection of your problem-solving prowess; showcase it proudly.", ["code is a reflection", "problem-solving prowess", "showcase it proudly"], required_words=["code is a reflection"])
    response("Coding is a conversation with machines; make it engaging and meaningful.", ["coding", "conversation with machines", "make it engaging", "meaningful"], required_words=["coding conversation"])
    response("The journey of coding is paved with challenges; conquer them and grow stronger.", ["journey of coding", "paved with challenges", "conquer them", "grow stronger"], required_words=["journey of coding"])
    response("Code is the building block of digital dreams; construct them with care and precision.", ["code", "building block of digital dreams", "construct them with care", "precision"], required_words=["code building block"])
    response("Coding is an art form; let your creativity flow through the lines of code.", ["coding", "art form", "let your creativity flow", "lines of code"], required_words=["coding"])
    response("Coding is a continuous exploration; there's always something new to discover.", ["coding", "continuous exploration", "new to discover"], required_words=["coding exploration"])
    response("Your coding journey is a story waiting to be written; what will the next chapter hold?", ["coding journey", "story waiting to be written", "next chapter"], required_words=["coding journey"])
    response("Code is the language of innovation; speak it boldly and shape the future.", ["code", "language of innovation", "speak it boldly", "shape the future"], required_words=["coding language"])
    response("In coding, each bug is a puzzle piece; solving them completes the picture.", ["coding", "bug is a puzzle piece", "solving them", "completes the picture"], required_words=["coding puzzle"])
    response("Every line of code is a step in the dance of creation; let's dance together.", ["line of code", "step in the dance of creation", "let's dance together"], required_words=["dance of creation"])
    response("Coding is like a journey through a maze; embrace the challenge and find your way.", ["coding", "journey through a maze", "embrace the challenge", "find your way"], required_words=["coding maze"])
    response("Your code is a symphony; conduct it with precision to create a harmonious result.", ["code is a symphony", "conduct it with precision", "harmonious result"], required_words=["code symphony"])
    response("Programming is a blend of strategy and creativity; play your moves wisely.", ["programming", "blend of strategy", "creativity", "play your moves wisely"], required_words=["programming strategy"])
    response("Coding is a dialogue with possibilities; let your code speak volumes.", ["coding", "dialogue with possibilities", "let your code speak volumes"], required_words=["coding dialogue"])
    response("In the world of coding, every challenge is a stepping stone to mastery; climb with determination.", ["world of coding", "challenge is a stepping stone", "mastery", "climb with determination"], required_words=["coding stepping stone"])
    response("I am an AI language model.", ["who", "are", "you"], required_words=["who"])
    response("The weather is indeed nice today.", ["weather"], required_words=["weather"])
    response("I'm here to assist you with coding.", ["coding", "help"], required_words=["coding"])
    response("I find that truly interesting!", ["interesting"], required_words=["interesting"])
    response("I'm here to help and assist you.", ["assist", "help"], required_words=["assist"])
    response("Absolutely! Coding is a fantastic skill to possess.", ["coding", "skill"], required_words=["coding"])
    response("I'm enjoying our conversation.", ["enjoy", "conversation"], required_words=["enjoy"])
    response("Learning new things is always an exciting journey.", ["learning", "exciting"], required_words=["learning"])
    response("Technology is advancing rapidly.", ["technology", "advancing"], required_words=["technology"])
    response("Curiosity is the key to learning.", ["curiosity", "learning"], required_words=["curiosity"])
    response("Stay curious and keep exploring!", ["stay", "curious", "exploring"], required_words=["curious"])
    response("I'm constantly learning and improving.", ["learning", "improving"], required_words=["learning"])
    response("Programming opens up a world of possibilities.", ["programming", "possibilities"], required_words=["programming"])
    response("Problem-solving is an essential skill in programming.", ["problem-solving", "programming"], required_words=["problem-solving"])
    response("Don't hesitate to ask if you have questions.", ["questions", "ask"], required_words=["questions"])
    response("I appreciate your curiosity.", ["appreciate", "curiosity"], required_words=["appreciate"])
    response("Keep up the good work!", ["keep up", "good work"], required_words=["keep up"])
    response("I recently watched a fascinating documentary about marine life; it was incredibly eye-opening.", ["watched", "fascinating documentary", "marine life", "eye-opening"], required_words=["watched"])
    response("Have you ever tried cooking a new recipe? I experimented with making homemade pizza last weekend.", ["tried cooking", "new recipe", "homemade pizza", "last weekend"], required_words=["tried cooking"])
    response("I'm a big fan of hiking. Nature has this amazing ability to recharge the mind, don't you think?", ["big fan of hiking", "nature", "recharge the mind"], required_words=["big fan"])
    response("Lately, I've been engrossed in reading science fiction novels. There's something magical about those imaginary worlds.", ["engrossed in reading", "science fiction novels", "imaginary worlds"], required_words=["engrossed"])
    response("I enjoy playing musical instruments; the piano has a special place in my heart. Do you have any favorite instruments?", ["enjoy playing musical instruments", "piano", "favorite instruments"], required_words=["enjoy playing"])
    response("Exploring local markets is one of my favorite pastimes. The vibrant colors and unique finds are always exciting.", ["exploring local markets", "favorite pastimes", "vibrant colors", "unique finds"], required_words=["exploring"])
    response("Last weekend, I attended an art exhibition featuring modern abstract paintings. It was a refreshing experience.", ["attended an art exhibition", "modern abstract paintings", "refreshing experience"], required_words=["attended"])
    response("I recently started practicing mindfulness meditation. It's incredible how it brings a sense of calm amid the chaos.", ["started practicing", "mindfulness meditation", "sense of calm", "amid the chaos"], required_words=["started practicing"])
    response("I love to travel and explore different cultures. Each journey is a treasure trove of unique experiences.", ["love to travel", "explore different cultures", "treasure trove", "unique experiences"], required_words=["love to travel"])
    response("I'm a bit of a movie buff. Any recent films that you found particularly interesting or entertaining?", ["movie buff", "recent films", "particularly interesting", "entertaining"], required_words=["movie buff"])
    response("I've been trying out new recipes lately. Do you have a favorite cuisine or dish you enjoy preparing?", ["trying out new recipes", "favorite cuisine", "dish", "enjoy preparing"], required_words=["trying out"])
    response("Have you ever explored virtual reality? I recently had the chance to try it, and it was mind-blowing!", ["explored virtual reality", "recently tried it", "mind-blowing"], required_words=["explored"])
    response("I've been listening to a podcast about space exploration. The universe is so vast and full of mysteries, don't you think?", ["listening to a podcast", "space exploration", "universe", "full of mysteries"], required_words=["listening to"])
    response("I'm a fan of board games. Do you have a go-to game for game nights with friends and family?", ["fan of board games", "go-to game", "game nights", "friends and family"], required_words=["fan of"])
    response("Recently, I visited an art gallery showcasing contemporary sculptures. It was awe-inspiring to see the creativity at play.", ["visited an art gallery", "contemporary sculptures", "awe-inspiring", "creativity at play"], required_words=["visited an"])
    response("I enjoy taking long walks in nature. It's a great way to clear the mind and appreciate the beauty around us.", ["enjoy taking long walks", "nature", "clear the mind", "appreciate the beauty"], required_words=["enjoy taking"])
    response("I've been reading a lot about sustainable living practices. Small changes can make a big impact, don't you think?", ["reading about sustainable living", "small changes", "make a big impact"], required_words=["reading about"])
    response("Ever tried stargazing? I find it incredibly calming to just lie down and gaze at the stars on a clear night.", ["tried stargazing", "incredibly calming", "gaze at the stars", "clear night"], required_words=["tried stargazing"])
    response("I recently attended a live music performance in the park. There's something magical about live music, isn't there?", ["attended a live music performance", "park", "magical", "live music"], required_words=["attended a"])
    response("I love gardening. Taking care of plants and seeing them flourish brings a sense of accomplishment.", ["love gardening", "taking care of plants", "seeing them flourish", "sense of accomplishment"], required_words=["love gardening"])
    response("I've been practicing mindfulness through yoga. It's amazing how it helps in finding balance and tranquility.", ["practicing mindfulness", "yoga", "helps in finding balance", "tranquility"], required_words=["practicing mindfulness"])
    response("Do you have any favorite podcasts? I'm always on the lookout for interesting ones to listen to during my free time.", ["favorite podcasts", "on the lookout", "interesting ones", "listen to during"], required_words=["favorite podcasts"])
    response("I enjoy DIY projects. There's a unique satisfaction in creating something with your own hands, don't you think?", ["enjoy DIY projects", "unique satisfaction", "creating something", "own hands"], required_words=["enjoy DIY"])
    response("I recently learned a few magic tricks. It's a fun way to entertain friends and family during gatherings.", ["learned a few magic tricks", "fun way to entertain", "friends and family", "during gatherings"], required_words=["learned a"])
    response("Coffee or tea? I'm a tea enthusiast myself. The variety of flavors is truly fascinating.", ["coffee or tea", "tea enthusiast", "variety of flavors", "truly fascinating"], required_words=["coffee or"])
    response("Have you ever tried a virtual escape room? It's a great way to challenge the mind and have fun with friends.", ["tried a virtual escape room", "challenge the mind", "have fun with friends"], required_words=["tried a"])
    response("I enjoy photography as a hobby. Capturing moments and expressing creativity through visuals is truly rewarding.", ["enjoy photography", "hobby", "capturing moments", "expressing creativity through"], required_words=["enjoy photography"])
    response("Recently, I've been exploring local farmers' markets. The fresh produce and unique finds are always delightful.", ["exploring local farmers' markets", "fresh produce", "unique finds", "always delightful"], required_words=["exploring local"])
    response("I've been watching a documentary series on ancient history. It's fascinating to learn about the civilizations that came before us.", ["watching a documentary series", "ancient history", "fascinating to learn", "civilizations that came before"], required_words=["watching a"])
    response("I'm a fan of classic literature. The timeless stories and rich language never fail to captivate me.", ["fan of classic literature", "timeless stories", "rich language", "never fail to captivate"], required_words=["fan of classic"])
    response("I've been exploring new hiking trails in the area. Nature has a way of rejuvenating the soul, don't you think?", ["exploring hiking trails", "nature", "rejuvenating the soul"], required_words=["exploring"])
    response("I recently attended a comedy show. Laughter is truly the best medicine, especially after a long day.", ["attended a comedy show", "laughter is the best medicine", "long day"], required_words=["attended a"])
    response("Have you ever tried your hand at cooking international cuisines? It's a flavorful journey for the taste buds.", ["tried cooking international cuisines", "flavorful journey", "taste buds"], required_words=["tried cooking"])
    response("I enjoy playing musical instruments, and recently, I picked up the ukulele. It brings such joy!", ["playing musical instruments", "picked up the ukulele", "brings joy"], required_words=["playing musical"])
    response("Exploring bookstores is one of my favorite pastimes. The smell of books and the endless possibilities on the shelves are captivating.", ["exploring bookstores", "favorite pastime", "smell of books", "endless possibilities"], required_words=["exploring"])
    response("I've been practicing mindfulness through meditation. It's amazing how it brings a sense of calm amidst the chaos.", ["practicing mindfulness through meditation", "sense of calm", "amidst the chaos"], required_words=["practicing mindfulness"])
    response("Recently, I started a small herb garden on my windowsill. Fresh herbs add a special touch to home-cooked meals.", ["started a small herb garden", "windowsill", "fresh herbs", "special touch"], required_words=["started a"])
    response("I'm a movie buff. Do you have a favorite genre or any must-watch recommendations?", ["movie buff", "favorite genre", "must-watch recommendations"], required_words=["movie buff"])
    response("I've been learning to paint. Expressing thoughts and emotions through art is a beautiful form of communication.", ["learning to paint", "expressing thoughts and emotions", "beautiful form of communication"], required_words=["learning to"])
    response("Recently, I delved into astronomy. The vastness of the cosmos is both humbling and awe-inspiring.", ["delved into astronomy", "vastness of the cosmos", "humbling and awe-inspiring"], required_words=["delved into"])
    response("I enjoy volunteering at local shelters. Making a positive impact in the community is truly fulfilling.", ["enjoy volunteering at local shelters", "positive impact in the community", "fulfilling"], required_words=["enjoy volunteering"])
    response("I love to travel. Exploring new cultures and cuisines broadens one's perspective, don't you think?", ["love to travel", "exploring new cultures", "cuisines broaden one's perspective"], required_words=["love to"])
    response("Recently, I've been into home decor. It's amazing how small changes can transform the feel of a space.", ["into home decor", "small changes", "transform the feel of a space"], required_words=["into home"])
    response("I'm a fan of board games. There's something special about the laughter and camaraderie they bring.", ["fan of board games", "laughter and camaraderie they bring"], required_words=["fan of"])
    response("I've been trying out new workout routines. Keeping active is essential for both physical and mental well-being.", ["trying out new workout routines", "keeping active", "physical and mental well-being"], required_words=["trying out"])
    response("Do you have any favorite podcasts? I'm always on the lookout for interesting ones to listen to during my free time.", ["favorite podcasts", "on the lookout", "interesting ones", "listen to during"], required_words=["favorite podcasts"])
    response("I enjoy DIY projects. There's a unique satisfaction in creating something with your own hands, don't you think?", ["enjoy DIY projects", "unique satisfaction", "creating something", "own hands"], required_words=["enjoy DIY"])
    response("I recently learned a few magic tricks. It's a fun way to entertain friends and family during gatherings.", ["learned a few magic tricks", "fun way to entertain", "friends and family", "during gatherings"], required_words=["learned a"])
    response("Coffee or tea? I'm a tea enthusiast myself. The variety of flavors is truly fascinating.", ["coffee or tea", "tea enthusiast", "variety of flavors", "truly fascinating"], required_words=["coffee or"])
    response("Have you ever tried a virtual escape room? It's a great way to challenge the mind and have fun with friends.", ["tried a virtual escape room", "challenge the mind", "have fun with friends"], required_words=["tried a"])
    response("I enjoy photography as a hobby. Capturing moments and expressing creativity through visuals is truly rewarding.", ["enjoy photography", "hobby", "capturing moments", "expressing creativity through"], required_words=["enjoy photography"])
    response("Recently, I've been exploring local farmers' markets. The fresh produce and unique finds are always delightful.", ["exploring local farmers' markets", "fresh produce", "unique finds", "always delightful"], required_words=["exploring local"])
    response("I've been watching a documentary series on ancient history. It's fascinating to learn about the civilizations that came before us.", ["watching a documentary series", "ancient history", "fascinating to learn", "civilizations that came before"], required_words=["watching a"])
    response("I'm a fan of classic literature. The timeless stories and rich language never fail to captivate me.", ["fan of classic literature", "timeless stories", "rich language", "never fail to captivate"], required_words=["fan of classic"])
    response("I've been exploring new hiking trails in the area. Nature has a way of rejuvenating the soul, don't you think?", ["exploring hiking trails", "nature", "rejuvenating the soul"], required_words=["exploring"])
    response("I recently attended a comedy show. Laughter is truly the best medicine, especially after a long day.", ["attended a comedy show", "laughter is the best medicine", "long day"], required_words=["attended a"])
    response("Have you ever tried your hand at cooking international cuisines? It's a flavorful journey for the taste buds.", ["tried cooking international cuisines", "flavorful journey", "taste buds"], required_words=["tried cooking"])
    response("I enjoy playing musical instruments, and recently, I picked up the ukulele. It brings such joy!", ["playing musical instruments", "picked up the ukulele", "brings joy"], required_words=["playing musical"])
    response("Exploring bookstores is one of my favorite pastimes. The smell of books and the endless possibilities on the shelves are captivating.", ["exploring bookstores", "favorite pastime", "smell of books", "endless possibilities"], required_words=["exploring"])
    response("I've been practicing mindfulness through meditation. It's amazing how it brings a sense of calm amidst the chaos.", ["practicing mindfulness through meditation", "sense of calm", "amidst the chaos"], required_words=["practicing mindfulness"])
    response("Recently, I started a small herb garden on my windowsill. Fresh herbs add a special touch to home-cooked meals.", ["started a small herb garden", "windowsill", "fresh herbs", "special touch"], required_words=["started a"])
    response("I'm a movie buff. Do you have a favorite genre or any must-watch recommendations?", ["movie buff", "favorite genre", "must-watch recommendations"], required_words=["movie buff"])
    response("I've been learning to paint. Expressing thoughts and emotions through art is a beautiful form of communication.", ["learning to paint", "expressing thoughts and emotions", "beautiful form of communication"], required_words=["learning to"])
    response("Recently, I delved into astronomy. The vastness of the cosmos is both humbling and awe-inspiring.", ["delved into astronomy", "vastness of the cosmos", "humbling and awe-inspiring"], required_words=["delved into"])
    response("I enjoy volunteering at local shelters. Making a positive impact in the community is truly fulfilling.", ["enjoy volunteering at local shelters", "positive impact in the community", "fulfilling"], required_words=["enjoy volunteering"])
    response("I love to travel. Exploring new cultures and cuisines broadens one's perspective, don't you think?", ["love to travel", "exploring new cultures", "cuisines broaden one's perspective"], required_words=["love to"])
    response("Recently, I've been into home decor. It's amazing how small changes can transform the feel of a space.", ["into home decor", "small changes", "transform the feel of a space"], required_words=["into home"])
    response("I'm a fan of board games. There's something special about the laughter and camaraderie they bring.", ["fan of board games", "laughter and camaraderie they bring"], required_words=["fan of"])
    response("I've been trying out new workout routines. Keeping active is essential for both physical and mental well-being.", ["trying out new workout routines", "keeping active", "physical and mental well-being"], required_words=["trying out"])
    response("Do you have any favorite podcasts? I'm always on the lookout for interesting ones to listen to during my free time.", ["favorite podcasts", "on the lookout", "interesting ones", "listen to during"], required_words=["favorite podcasts"])
    response("I enjoy DIY projects. There's a unique satisfaction in creating something with your own hands, don't you think?", ["enjoy DIY projects", "unique satisfaction", "creating something", "own hands"], required_words=["enjoy DIY"])
    response("I recently learned a few magic tricks. It's a fun way to entertain friends and family during gatherings.", ["learned a few magic tricks", "fun way to entertain", "friends and family", "during gatherings"], required_words=["learned a"])
    response("Coffee or tea? I'm a tea enthusiast myself. The variety of flavors is truly fascinating.", ["coffee or tea", "tea enthusiast", "variety of flavors", "truly fascinating"], required_words=["coffee or"])
    response("Have you ever tried a virtual escape room? It's a great way to challenge the mind and have fun with friends.", ["tried a virtual escape room", "challenge the mind", "have fun with friends"], required_words=["tried a"])
    response("I enjoy photography as a hobby. Capturing moments and expressing creativity through visuals is truly rewarding.", ["enjoy photography", "hobby", "capturing moments", "expressing creativity through"], required_words=["enjoy photography"])
    response("Recently, I've been exploring local farmers' markets. The fresh produce and unique finds are always delightful.", ["exploring local farmers' markets", "fresh produce", "unique finds", "always delightful"], required_words=["exploring local"])
    response("I've been watching a documentary series on ancient history. It's fascinating to learn about the civilizations that came before us.", ["watching a documentary series", "ancient history", "fascinating to learn", "civilizations that came before"], required_words=["watching a"])
    response("I'm a fan of classic literature. The timeless stories and rich language never fail to captivate me.", ["fan of classic literature", "timeless stories", "rich language", "never fail to captivate"], required_words=["fan of classic"])
    response("I've been exploring new hiking trails in the area. Nature has a way of rejuvenating the soul, don't you think?", ["exploring hiking trails", "nature", "rejuvenating the soul"], required_words=["exploring"])
    response("I recently attended a comedy show. Laughter is truly the best medicine, especially after a long day.", ["attended a comedy show", "laughter is the best medicine", "long day"], required_words=["attended a"])
    response("Have you ever tried your hand at cooking international cuisines? It's a flavorful journey for the taste buds.", ["tried cooking international cuisines", "flavorful journey", "taste buds"], required_words=["tried cooking"])
    response("I enjoy playing musical instruments, and recently, I picked up the ukulele. It brings such joy!", ["playing musical instruments", "picked up the ukulele", "brings joy"], required_words=["playing musical"])
    response("Exploring bookstores is one of my favorite pastimes. The smell of books and the endless possibilities on the shelves are captivating.", ["exploring bookstores", "favorite pastime", "smell of books", "endless possibilities"], required_words=["exploring"])
    response("I've been practicing mindfulness through meditation. It's amazing how it brings a sense of calm amidst the chaos.", ["practicing mindfulness through meditation", "sense of calm", "amidst the chaos"], required_words=["practicing mindfulness"])
    response("Recently, I started a small herb garden on my windowsill. Fresh herbs add a special touch to home-cooked meals.", ["started a small herb garden", "windowsill", "fresh herbs", "special touch"], required_words=["started a"])
    response("I'm a movie buff. Do you have a favorite genre or any must-watch recommendations?", ["movie"])




    best_match = max(highest_prob_list, key=highest_prob_list.get)
    print(highest_prob_list)

    
    return best_match
    #return long.unknown() if highest_prob_list[best_match] < 1 else best_match


def get_response(user_input):
    split_message = re.split(r'\s+|[,;?!.-]\s*', user_input.lower())
    response = check_all_messages(split_message)
    return response

# testing the response system
"""while True:
    print(get_response(input('YOU :')"""
